language: php
sudo: required

services:
    - docker

matrix:
    include:
        - env: MODE=php
          php: 5.5
        - env: MODE=php
          php: 5.6
        - env: MODE=php
          php: 7.0
        - env: MODE=php
          php: 7.1
        - env: MODE=docker

before_script:
    - if [ "$MODE" = "php" ]; then yes '' | sudo apt-get install libzmq-dev; fi
    - if [ "$MODE" = "php" ]; then yes '' | pecl install -f zmq; fi
    - if [ "$MODE" = "php" ]; then composer update; fi

script:
    - if [ "$MODE" = "docker" ]; then make; fi

script:
    - if [ "$MODE" = "php" ]; then ./vendor/bin/phpcs --standard=phpcs.xml src; fi
    - if [ "$MODE" = "php" ]; then ./vendor/bin/phpunit -c .; fi
